version: "3.7"
services:
  spark-master:
    stdin_open: true
    tty: true
    image: spark-master:2.3.1
    container_name: spark-master
    hostname: spark-master
    network_mode: "host"
    volumes:
       - /mnt/spark-apps:/opt/spark-apps
       - /mnt/spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=192.168.1.131"
  spark-worker-1:
    image: spark-worker:2.3.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=192.168.1.131"
    network_mode: "host"
    volumes:
       - /mnt/spark-apps:/opt/spark-apps
       - /mnt/spark-data:/opt/spark-data
         
